-- Glossary terms table for SEO knowledge base
CREATE TABLE IF NOT EXISTS glossary_terms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  term TEXT UNIQUE NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  short_definition TEXT NOT NULL,
  full_explanation TEXT NOT NULL DEFAULT '',
  examples JSONB DEFAULT '[]'::jsonb,
  related_terms JSONB DEFAULT '[]'::jsonb,
  category TEXT NOT NULL DEFAULT 'general',
  difficulty TEXT NOT NULL DEFAULT 'beginner',
  status TEXT NOT NULL DEFAULT 'published',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_glossary_terms_slug ON glossary_terms(slug);
CREATE INDEX IF NOT EXISTS idx_glossary_terms_category ON glossary_terms(category);
CREATE INDEX IF NOT EXISTS idx_glossary_terms_status ON glossary_terms(status);

-- Enable RLS
ALTER TABLE glossary_terms ENABLE ROW LEVEL SECURITY;

-- Public read access for published terms
CREATE POLICY "Public can read published glossary terms"
  ON glossary_terms FOR SELECT
  USING (status = 'published');

-- Seed initial glossary terms
INSERT INTO glossary_terms (term, slug, short_definition, full_explanation, category, difficulty, related_terms) VALUES

-- Technical SEO
('Canonical URL', 'canonical-url', 'An HTML element that tells search engines which URL is the preferred version of a page.', 'A canonical URL (rel="canonical") is an HTML link element that helps prevent duplicate content issues by telling search engines which version of a page should be indexed. When multiple URLs serve identical or very similar content — such as pages with URL parameters, print versions, or mobile variants — the canonical tag consolidates ranking signals to the preferred URL. Without canonical tags, search engines may index multiple versions of the same page, diluting your ranking potential and wasting crawl budget. Implementing canonical tags correctly is one of the most impactful technical SEO optimizations for sites with dynamic URLs or content syndication.', 'technical-seo', 'intermediate', '["robots-txt", "crawl-budget", "indexing", "sitemap"]'),

('Crawl Budget', 'crawl-budget', 'The number of pages a search engine will crawl on your site within a given timeframe.', 'Crawl budget refers to the number of pages Googlebot (or other search engine crawlers) will visit on your website within a specific period. It is determined by two factors: crawl rate limit (how fast the crawler can go without overloading your server) and crawl demand (how much Google wants to crawl your site based on popularity and freshness). For most small-to-medium sites, crawl budget is not a concern. However, for large sites with millions of pages — e-commerce stores, news publishers, or user-generated content platforms — managing crawl budget is critical. Techniques include blocking unnecessary pages via robots.txt, fixing redirect chains, improving server response times, and ensuring internal linking guides crawlers to important pages.', 'technical-seo', 'advanced', '["robots-txt", "sitemap", "indexing", "internal-linking"]'),

('Robots.txt', 'robots-txt', 'A text file that instructs search engine crawlers which pages they can or cannot access.', 'Robots.txt is a file placed at the root of your website (example.com/robots.txt) that provides instructions to search engine crawlers about which areas of your site they should or should not visit. It uses simple directives like Allow, Disallow, and Sitemap to guide crawlers. While robots.txt can prevent crawling, it does not prevent indexing — a page blocked by robots.txt can still appear in search results if other pages link to it. For preventing indexing, use the noindex meta tag instead. Common uses include blocking admin areas, search result pages, and duplicate content from being crawled.', 'technical-seo', 'beginner', '["crawl-budget", "sitemap", "indexing", "canonical-url"]'),

('Sitemap', 'sitemap', 'An XML file that lists all important pages on your website to help search engines discover and crawl them.', 'An XML sitemap is a structured file that lists the URLs on your website along with metadata like last modification date, change frequency, and priority. It helps search engines discover pages that might be hard to find through normal crawling, especially on large or new sites. Dynamic sitemaps that automatically update when content is added or changed are recommended over static ones. Submit your sitemap through Google Search Console and reference it in your robots.txt file. For large sites, sitemap indexes can organize multiple sitemaps by section (blog, products, categories).', 'technical-seo', 'beginner', '["robots-txt", "crawl-budget", "indexing"]'),

('Core Web Vitals', 'core-web-vitals', 'A set of three metrics that measure real-world user experience: loading speed (LCP), interactivity (INP), and visual stability (CLS).', 'Core Web Vitals are a set of specific page experience metrics that Google uses as a ranking signal. They measure three aspects of user experience: Largest Contentful Paint (LCP) measures loading performance — how long it takes for the main content to appear. Interaction to Next Paint (INP) measures responsiveness — how quickly the page responds to user input. Cumulative Layout Shift (CLS) measures visual stability — how much the page layout shifts unexpectedly during loading. Good scores are LCP under 2.5 seconds, INP under 200 milliseconds, and CLS under 0.1. Improving Core Web Vitals involves optimizing images, reducing JavaScript, using efficient CSS, implementing lazy loading, and choosing fast hosting.', 'technical-seo', 'intermediate', '["page-speed", "mobile-optimization", "indexing"]'),

('Indexing', 'indexing', 'The process by which search engines store and organize web pages in their database for retrieval in search results.', 'Indexing is the process where search engines analyze, process, and store web page content in their databases. When a page is indexed, it becomes eligible to appear in search results. A page must first be crawled (discovered), then processed (content analyzed, links extracted), and finally added to the index. Pages can be excluded from indexing using the noindex meta tag or X-Robots-Tag header. Common indexing issues include blocked resources (CSS/JS), noindex tags, redirect loops, and server errors. Monitor your index coverage in Google Search Console to identify and fix indexing problems.', 'technical-seo', 'beginner', '["crawl-budget", "robots-txt", "sitemap", "canonical-url"]'),

('Structured Data', 'structured-data', 'Code markup (typically JSON-LD) that helps search engines understand your content and display rich results.', 'Structured data is code in a specific format (typically JSON-LD, but also Microdata or RDFa) that you add to your pages to help search engines understand the content more clearly. Using schemas from Schema.org, you can mark up content types like articles, products, reviews, FAQs, events, recipes, and organizations. When search engines understand your content structure, they can display rich results — enhanced search listings with star ratings, prices, FAQ dropdowns, images, and more. Rich results significantly increase click-through rates, sometimes by 30% or more. Google recommends JSON-LD format and provides a Rich Results Test tool to validate your markup.', 'technical-seo', 'intermediate', '["json-ld", "rich-results", "indexing"]'),

('Hreflang', 'hreflang', 'An HTML attribute that tells search engines which language and regional version of a page to show to users.', 'Hreflang is an HTML attribute used to specify the language and geographic targeting of a webpage. It helps search engines serve the correct language version of your content to users in different regions. For example, you might have English content for the US (en-US), English content for the UK (en-GB), and Spanish content for Spain (es-ES). Without hreflang tags, search engines might show the wrong language version, or flag your pages as duplicate content. Implementing hreflang requires adding link elements in the HTML head, HTTP headers, or sitemap, and must be bidirectional — each page must reference all other language versions, including itself.', 'technical-seo', 'advanced', '["canonical-url", "international-seo"]'),

-- On-Page SEO
('Meta Description', 'meta-description', 'An HTML tag that provides a brief summary of a page, displayed as the snippet in search results.', 'A meta description is an HTML meta tag that provides a concise summary of a web page content. It typically appears as the descriptive text snippet below the title in search engine results pages (SERPs). While meta descriptions are not a direct ranking factor, they significantly influence click-through rates. A well-written meta description should be 70-160 characters, include your target keyword naturally, contain a clear value proposition, and end with a call to action. Google sometimes overrides your meta description with content it considers more relevant to the user query, especially if the provided description does not match the search intent.', 'on-page-seo', 'beginner', '["title-tag", "serp", "click-through-rate"]'),

('Title Tag', 'title-tag', 'The HTML title element that defines a page''s title, displayed in search results and browser tabs.', 'The title tag is an HTML element that specifies the title of a web page. It is one of the most important on-page SEO factors because it appears as the clickable headline in search results, in browser tabs, and when pages are shared on social media. Best practices include keeping titles between 30-60 characters, placing your primary keyword near the beginning, making each page title unique, and writing compelling copy that encourages clicks. Google may rewrite your title tag if it considers it too long, keyword-stuffed, or not representative of the page content. A well-optimized title tag can improve both rankings and click-through rates.', 'on-page-seo', 'beginner', '["meta-description", "serp", "click-through-rate", "on-page-seo"]'),

('Alt Text', 'alt-text', 'Descriptive text added to HTML image tags that describes the image content for search engines and accessibility.', 'Alt text (alternative text) is a text description added to the alt attribute of an HTML image tag. It serves two primary purposes: accessibility (screen readers use it to describe images to visually impaired users) and SEO (search engines use it to understand image content since they cannot see images). Good alt text is descriptive, concise (under 125 characters), includes relevant keywords naturally, and accurately describes what the image shows. Avoid keyword stuffing in alt text — it should read naturally as a description. Images without alt text are missed SEO opportunities and accessibility violations.', 'on-page-seo', 'beginner', '["on-page-seo", "image-seo"]'),

('Internal Linking', 'internal-linking', 'Links from one page on your website to another page on the same website, helping distribute authority and guide navigation.', 'Internal linking is the practice of creating hyperlinks between pages on the same website. It serves multiple purposes: helping users navigate your site, distributing page authority (link equity) throughout your site, establishing content hierarchy and topic relationships, and helping search engines discover and understand your content. Effective internal linking strategies include using descriptive anchor text (not "click here"), linking from high-authority pages to important pages, creating topic clusters with pillar pages and supporting content, and ensuring every page is reachable within 3 clicks from the homepage. Well-structured internal linking can significantly improve rankings for target keywords.', 'on-page-seo', 'intermediate', '["anchor-text", "link-equity", "crawl-budget"]'),

('Heading Tags', 'heading-tags', 'HTML elements (H1-H6) that structure content hierarchically, helping both users and search engines understand page organization.', 'Heading tags (H1 through H6) are HTML elements that define the structure and hierarchy of content on a web page. The H1 tag represents the main topic of the page and should typically appear only once. H2 tags denote major sections, H3 tags denote subsections within H2 sections, and so on. Search engines use heading tags to understand the topical structure of your content. Best practices include using one H1 per page that includes your primary keyword, structuring H2-H6 tags logically (never skip levels), including relevant keywords in headings naturally, and making headings descriptive and useful for users scanning the page.', 'on-page-seo', 'beginner', '["on-page-seo", "title-tag", "content-optimization"]'),

('Keyword Density', 'keyword-density', 'The percentage of times a target keyword appears on a page relative to the total word count.', 'Keyword density is calculated by dividing the number of times a keyword appears on a page by the total number of words, then multiplying by 100. For example, if a keyword appears 10 times in a 1,000-word article, the density is 1%. While there is no ideal keyword density, most SEO professionals recommend keeping primary keywords at 1-2%. Density above 3% may be flagged as keyword stuffing. Modern search engines use natural language processing (NLP) and semantic understanding, making exact keyword density less important than topical relevance, semantic variations, and comprehensive content coverage. Focus on writing naturally while ensuring your target keyword and related terms appear throughout the content.', 'on-page-seo', 'beginner', '["on-page-seo", "content-optimization", "keyword-stuffing"]'),

('Featured Snippet', 'featured-snippet', 'A highlighted search result that appears at the top of Google''s results, providing a direct answer to a query.', 'A featured snippet is a special search result format that appears at the top of Google''s organic results (position zero). It extracts and displays a direct answer to a user''s query from a web page, along with the page title and URL. Featured snippets come in several formats: paragraph (a text block answering the question), list (numbered or bulleted steps), table (structured data comparison), and video (YouTube clips). To optimize for featured snippets, structure your content with clear questions as headings followed by concise answers, use lists and tables where appropriate, answer questions directly in 40-60 words, and target question-based keywords.', 'on-page-seo', 'intermediate', '["serp", "answer-engine-optimization", "content-optimization"]'),

-- Off-Page SEO
('Backlink', 'backlink', 'A link from one website to another, serving as a vote of confidence that influences search engine rankings.', 'A backlink (also called an inbound link or incoming link) is a hyperlink from one website pointing to a page on another website. Search engines treat backlinks as votes of confidence — the more high-quality, relevant backlinks a page has, the more likely it is to rank well. Not all backlinks are equal: links from authoritative, topically relevant websites carry significantly more weight than links from low-quality or unrelated sites. Key backlink metrics include domain authority of the linking site, relevance of the linking page, anchor text used, link placement (editorial vs. sidebar/footer), and whether the link is dofollow or nofollow. Building high-quality backlinks is one of the most impactful SEO activities.', 'off-page-seo', 'beginner', '["domain-authority", "anchor-text", "link-building", "nofollow"]'),

('Domain Authority', 'domain-authority', 'A score (0-100) predicting how likely a website is to rank in search results, based on backlink profile and other factors.', 'Domain Authority (DA) is a search engine ranking score developed by Moz that predicts how likely a website is to rank in search engine result pages. It is calculated on a logarithmic scale from 0 to 100, with higher scores indicating greater ranking potential. DA is based on multiple factors including the number and quality of backlinks, linking root domains, and overall link profile strength. While DA is not a Google ranking factor, it is a useful comparative metric for evaluating the competitive strength of a domain relative to others. Improving DA requires building high-quality backlinks from authoritative sites, removing toxic backlinks, and creating content that naturally attracts links over time.', 'off-page-seo', 'beginner', '["backlink", "link-building", "page-authority"]'),

('Anchor Text', 'anchor-text', 'The clickable text in a hyperlink that provides context about the linked page''s content to users and search engines.', 'Anchor text is the visible, clickable text in a hyperlink. Search engines use anchor text to understand what the linked page is about, making it an important signal for relevance. Types of anchor text include: exact match (uses the target keyword), partial match (includes the target keyword with additional words), branded (uses the brand name), generic (uses phrases like "click here" or "learn more"), naked URL (uses the raw URL), and image (the image alt text serves as anchor text). A natural backlink profile contains a diverse mix of anchor text types. Over-optimization (too many exact match anchors) can trigger Google penalties. For internal links, use descriptive anchor text that helps both users and search engines understand the destination page.', 'off-page-seo', 'intermediate', '["backlink", "internal-linking", "link-building"]'),

('Link Building', 'link-building', 'The process of acquiring hyperlinks from other websites to your own, improving search engine authority and rankings.', 'Link building is the SEO practice of acquiring backlinks from external websites to improve your site''s authority and rankings. Effective link building strategies include: creating linkable assets (original research, free tools, comprehensive guides), guest posting on authoritative sites, digital PR and media outreach, broken link building (finding broken links and offering your content as a replacement), resource page outreach, and building relationships with industry peers. Quality matters far more than quantity — a single link from a high-authority, relevant site can be more valuable than dozens of low-quality links. Avoid manipulative link schemes like link farms, paid links, or excessive link exchanges, as these can result in manual penalties from Google.', 'off-page-seo', 'intermediate', '["backlink", "domain-authority", "anchor-text", "nofollow"]'),

('Nofollow', 'nofollow', 'A link attribute (rel="nofollow") that tells search engines not to pass ranking authority through the link.', 'The nofollow attribute (rel="nofollow") is an HTML value added to links to tell search engines not to pass PageRank (ranking authority) through that link. Google introduced nofollow in 2005 to combat comment spam. Since 2019, Google treats nofollow as a hint rather than a directive, meaning it may still consider nofollow links for crawling and indexing purposes. Related attributes include rel="sponsored" (for paid or sponsored links) and rel="ugc" (for user-generated content like comments and forum posts). While nofollow links don''t directly pass authority, they can still drive referral traffic, brand awareness, and may indirectly contribute to SEO through increased visibility and natural link acquisition.', 'off-page-seo', 'intermediate', '["backlink", "link-building", "link-equity"]'),

('Link Equity', 'link-equity', 'The ranking authority that is passed from one page to another through hyperlinks, also known as link juice.', 'Link equity (commonly called "link juice") refers to the ranking value that is passed from one page to another through hyperlinks. When a page links to another page, it passes a portion of its authority. The amount of link equity passed depends on several factors: the authority of the linking page, the number of outbound links on the page (equity is divided among all links), the relevance of the linking page to the destination page, and whether the link is dofollow or nofollow. Internal links also pass link equity, which is why strategic internal linking — directing equity from high-authority pages to important target pages — is a fundamental SEO practice.', 'off-page-seo', 'advanced', '["backlink", "internal-linking", "domain-authority", "nofollow"]'),

-- Content Marketing
('E-E-A-T', 'eeat', 'Experience, Expertise, Authoritativeness, and Trustworthiness — Google''s framework for evaluating content quality.', 'E-E-A-T stands for Experience, Expertise, Authoritativeness, and Trustworthiness. It is a framework from Google''s Search Quality Evaluator Guidelines used by human quality raters to assess content quality. While not a direct ranking algorithm, E-E-A-T signals influence how Google''s algorithms evaluate content, especially for YMYL (Your Money or Your Life) topics like health, finance, and legal advice. Experience means the content creator has first-hand experience with the topic. Expertise means they have relevant knowledge or credentials. Authoritativeness means the site and author are recognized as authoritative sources. Trustworthiness means the content and site are reliable and accurate. Improving E-E-A-T involves displaying author credentials, citing reputable sources, maintaining accurate information, earning backlinks from authoritative sites, and showcasing real-world experience.', 'content-marketing', 'intermediate', '["content-optimization", "on-page-seo"]'),

('Content Gap', 'content-gap', 'Topics or keywords that competitors rank for but your website does not, representing opportunities for new content.', 'A content gap is a topic, keyword, or piece of information that your target audience is searching for but your website does not adequately cover. Content gap analysis compares your site''s keyword coverage against competitors to identify opportunities where you could create content to capture additional organic traffic. The process involves: identifying your top competitors, comparing the keywords they rank for against your own, finding high-value keywords where competitors rank but you don''t, and creating comprehensive content targeting those gaps. Content gap analysis is one of the most efficient ways to prioritize content creation because it focuses on topics with proven search demand that you have a realistic chance of ranking for.', 'content-marketing', 'intermediate', '["keyword-research", "competitor-analysis", "content-optimization"]'),

('Pillar Page', 'pillar-page', 'A comprehensive, authoritative page that covers a broad topic in depth and links to related cluster content.', 'A pillar page is a comprehensive, long-form page that covers a broad topic thoroughly and serves as the central hub in a topic cluster content strategy. The pillar page links to more specific, related articles (cluster content) that dive deeper into subtopics, and those cluster pages link back to the pillar. This hub-and-spoke structure signals topical authority to search engines. Pillar pages are typically 3,000-5,000+ words and cover a topic broadly, while cluster content pages are more focused and detailed on specific aspects. For example, a pillar page on "SEO" might link to cluster pages about "keyword research," "technical SEO," "link building," and "content optimization."', 'content-marketing', 'intermediate', '["internal-linking", "content-optimization", "topic-cluster"]'),

('Topic Cluster', 'topic-cluster', 'A content strategy organizing pages around a central pillar page with supporting cluster content linked together.', 'A topic cluster is a content organization strategy where a central pillar page covers a broad topic comprehensively, while multiple cluster pages explore specific subtopics in greater detail. All cluster pages link back to the pillar page, and the pillar links to all cluster pages, creating a tightly interlinked content structure. This approach signals to search engines that your site has deep expertise on the topic, boosting rankings for the entire cluster. Topic clusters have replaced the old approach of creating isolated pages targeting individual keywords. By organizing content semantically around topics rather than keywords, you build topical authority that helps all related pages rank better.', 'content-marketing', 'intermediate', '["pillar-page", "internal-linking", "content-optimization"]'),

-- AI Search
('Answer Engine Optimization', 'answer-engine-optimization', 'The practice of optimizing content to appear in AI-generated answers from search engines and AI assistants.', 'Answer Engine Optimization (AEO) is the practice of optimizing content so it is selected and cited by AI-powered answer engines like Google''s AI Overviews, ChatGPT, Perplexity, and other AI assistants. Unlike traditional SEO which focuses on ranking blue links, AEO focuses on getting your content directly referenced in AI-generated answers. Key AEO strategies include: structuring content in clear question-and-answer formats, providing concise, authoritative answers to common questions, using structured data (FAQ schema, HowTo schema) to help AI understand your content, building topical authority through comprehensive coverage, and ensuring your content is factually accurate with proper citations.', 'ai-search', 'intermediate', '["generative-engine-optimization", "featured-snippet", "structured-data"]'),

('Generative Engine Optimization', 'generative-engine-optimization', 'Optimizing content to be cited and referenced by generative AI search engines like ChatGPT, Perplexity, and Gemini.', 'Generative Engine Optimization (GEO) is the emerging practice of optimizing content specifically for generative AI search engines that create synthesized answers from multiple sources. Unlike traditional search where users click through to websites, generative search engines like ChatGPT, Perplexity, Google Gemini, and Microsoft Copilot compile information and present it directly to users with source citations. GEO strategies include: creating unique, authoritative content that AI models reference, establishing strong entity presence in knowledge bases, building brand mentions across the web, optimizing for topical authority and E-E-A-T signals, and monitoring AI search citations to understand how and when your content is referenced.', 'ai-search', 'advanced', '["answer-engine-optimization", "eeat", "ai-visibility"]'),

('AI Visibility', 'ai-visibility', 'A measure of how often and prominently your brand or content appears in AI-generated search results and recommendations.', 'AI visibility refers to how visible your brand, website, or content is within AI-generated search results and recommendations. As AI search engines like ChatGPT, Perplexity, Google Gemini, and Microsoft Copilot become primary search tools for many users, tracking your visibility in these platforms is becoming as important as tracking traditional Google rankings. AI visibility metrics include: how often your brand is mentioned in AI responses, whether your content is cited as a source, the sentiment of AI-generated mentions, and which queries trigger mentions of your brand. Improving AI visibility requires building topical authority, creating unique authoritative content, maintaining strong E-E-A-T signals, and monitoring AI citations over time.', 'ai-search', 'intermediate', '["answer-engine-optimization", "generative-engine-optimization", "eeat"]'),

('Knowledge Graph', 'knowledge-graph', 'A database of facts and relationships that search engines use to understand entities and provide direct answers.', 'A knowledge graph is a structured database that search engines use to store information about real-world entities (people, places, organizations, concepts) and the relationships between them. Google''s Knowledge Graph powers the information panels that appear on the right side of search results, providing quick facts about entities. Getting your brand or organization into Google''s Knowledge Graph increases visibility and authority. Strategies include: having a Wikipedia page, maintaining consistent information across authoritative sources, using structured data (Organization, Person, Product schemas), claiming your Google Business Profile, and building brand mentions across the web.', 'ai-search', 'advanced', '["structured-data", "eeat", "ai-visibility"]'),

-- Analytics
('Organic Traffic', 'organic-traffic', 'Website visitors who arrive through unpaid search engine results rather than paid advertisements.', 'Organic traffic refers to visitors who reach your website by clicking on unpaid (organic) search engine results. It is typically the most valuable traffic source because it represents users actively searching for information, products, or services related to your content. Organic traffic is tracked through analytics tools like Google Analytics, where it is distinguished from other traffic sources like paid search, social media, referral, and direct traffic. Growing organic traffic is the primary goal of SEO. Key metrics to track include total organic sessions, organic keywords driving traffic, landing pages receiving organic visits, organic conversion rate, and year-over-year organic traffic growth.', 'analytics', 'beginner', '["serp", "click-through-rate", "keyword-research"]'),

('Click-Through Rate', 'click-through-rate', 'The percentage of users who click on your search result after seeing it, calculated as clicks divided by impressions.', 'Click-through rate (CTR) in SEO context is the percentage of users who click on your search result after seeing it in the SERPs. It is calculated by dividing the number of clicks by the number of impressions (times your result was shown) and multiplying by 100. For example, if your page appears 1,000 times and receives 50 clicks, your CTR is 5%. Average CTR varies significantly by position: position 1 averages about 28% CTR, position 2 about 15%, and position 10 about 2.5%. Improving CTR involves writing compelling title tags and meta descriptions, using structured data for rich results, and matching search intent. A higher CTR can indirectly improve rankings as it signals to search engines that your result is relevant.', 'analytics', 'beginner', '["serp", "meta-description", "title-tag", "organic-traffic"]'),

('Search Volume', 'search-volume', 'The estimated number of times a keyword is searched per month, indicating demand and traffic potential.', 'Search volume is a metric that estimates how many times a particular keyword is searched per month in a given search engine (typically Google). It is one of the most important metrics in keyword research as it indicates the potential traffic you could receive by ranking for that keyword. Search volume data is typically provided by tools that aggregate and estimate from multiple data sources including Google Ads data, clickstream data, and search trend data. Important considerations: search volume varies by location and language, seasonal keywords have fluctuating volumes, long-tail keywords have lower individual volume but collectively drive significant traffic, and volume alone does not indicate value — CPC and intent matter equally.', 'analytics', 'beginner', '["keyword-research", "keyword-difficulty", "click-through-rate"]'),

('Keyword Difficulty', 'keyword-difficulty', 'A score (0-100) estimating how hard it would be to rank in the top 10 search results for a given keyword.', 'Keyword difficulty (KD) is a metric that estimates how challenging it would be to rank in the top organic results for a specific keyword. It is typically scored on a scale of 0-100, where higher scores indicate greater competition. Keyword difficulty is calculated based on factors like the domain authority of currently ranking pages, the quality and quantity of their backlinks, content relevance, and SERP features present. When planning content strategy, balance keyword difficulty with search volume and business value. New or low-authority sites should target keywords with difficulty under 30, while established sites with strong backlink profiles can compete for keywords with difficulty scores of 60+.', 'analytics', 'beginner', '["keyword-research", "search-volume", "domain-authority"]'),

('SERP', 'serp', 'Search Engine Results Page — the page displayed by a search engine in response to a user query.', 'SERP stands for Search Engine Results Page, which is the page a search engine displays after a user submits a query. Modern SERPs contain much more than the traditional ten blue links. They can include: organic results, paid ads (top and bottom), featured snippets (position zero), knowledge panels, People Also Ask boxes, image packs, video carousels, local map packs, shopping results, news results, and AI-generated overviews. Understanding SERP features for your target keywords is crucial because they affect click-through rates and traffic potential. Some SERP features (like featured snippets) can drive significant traffic, while others (like direct answers) may reduce clicks to websites.', 'analytics', 'beginner', '["organic-traffic", "featured-snippet", "click-through-rate", "keyword-research"]'),

('Bounce Rate', 'bounce-rate', 'The percentage of visitors who leave your website after viewing only one page without taking any further action.', 'Bounce rate is a web analytics metric that measures the percentage of visitors who enter your site and leave without viewing any other pages or taking any meaningful action. In Google Analytics 4 (GA4), this has been replaced by "engagement rate" — the percentage of engaged sessions (sessions lasting more than 10 seconds, having a conversion event, or viewing 2+ pages). A high bounce rate can indicate poor content relevance, slow page load times, bad user experience, or misleading search result snippets. However, bounce rate must be interpreted in context — a blog post that fully answers a user''s question may have a high bounce rate but still provide excellent user value.', 'analytics', 'beginner', '["organic-traffic", "click-through-rate", "core-web-vitals"]'),

('Impressions', 'impressions', 'The number of times your page or content appears in search results, regardless of whether users click on it.', 'Impressions in SEO refer to the number of times your page appears in search engine results, whether or not the user clicks on your result. Impressions are tracked in Google Search Console and provide insight into your visibility for specific queries. A page receives an impression each time it appears in the search results that a user views — even if the user does not scroll down to see your result. Analyzing impressions alongside clicks and CTR helps identify opportunities: high impressions with low CTR may indicate that your title tag or meta description needs improvement, while growing impressions signal increasing visibility for your target keywords.', 'analytics', 'beginner', '["click-through-rate", "serp", "organic-traffic", "search-volume"]'),

-- Additional important terms
('Keyword Research', 'keyword-research', 'The process of finding and analyzing search terms that people use in search engines to inform content strategy.', 'Keyword research is the foundational SEO process of discovering, analyzing, and selecting search terms that your target audience uses when looking for information, products, or services. Effective keyword research involves: identifying seed keywords related to your business, expanding those seeds using keyword research tools, analyzing search volume, difficulty, CPC, and intent for each keyword, grouping keywords by topic and intent, and prioritizing keywords based on business value and ranking potential. Modern keyword research goes beyond individual keywords to focus on topics and search intent. A comprehensive keyword research process also includes analyzing competitor keywords, identifying content gaps, and understanding seasonal trends.', 'on-page-seo', 'beginner', '["search-volume", "keyword-difficulty", "content-gap", "serp"]'),

('Mobile Optimization', 'mobile-optimization', 'The practice of ensuring your website provides an excellent experience on mobile devices, which is critical for search rankings.', 'Mobile optimization is the process of designing and configuring your website to provide an excellent user experience on smartphones and tablets. Since Google uses mobile-first indexing (it primarily uses the mobile version of your site for ranking and indexing), mobile optimization is no longer optional — it is essential for SEO. Key aspects include responsive design that adapts to all screen sizes, fast mobile page speed (Core Web Vitals), touch-friendly navigation and buttons, readable text without zooming, no intrusive interstitials (popups), and proper viewport configuration. Test your mobile optimization using Google PageSpeed Insights and the Mobile-Friendly Test tool.', 'technical-seo', 'beginner', '["core-web-vitals", "page-speed", "indexing"]'),

('Page Speed', 'page-speed', 'How quickly a web page loads and becomes interactive, measured by metrics like LCP, FCP, and Time to Interactive.', 'Page speed refers to how quickly a web page''s content loads and becomes interactive for users. It is both a direct Google ranking factor and a critical user experience metric. Page speed is measured through several metrics: First Contentful Paint (FCP), Largest Contentful Paint (LCP), Time to Interactive (TTI), and Total Blocking Time (TBT). Improving page speed involves: optimizing and compressing images, minifying CSS, JavaScript, and HTML, leveraging browser caching, using a content delivery network (CDN), reducing server response time, implementing lazy loading for below-the-fold content, and eliminating render-blocking resources. Google PageSpeed Insights and Lighthouse are free tools for analyzing and improving page speed.', 'technical-seo', 'intermediate', '["core-web-vitals", "mobile-optimization"]'),

('JSON-LD', 'json-ld', 'JavaScript Object Notation for Linked Data — the recommended format for implementing structured data on web pages.', 'JSON-LD (JavaScript Object Notation for Linked Data) is the format recommended by Google for implementing structured data on web pages. It uses a script tag in the HTML head or body to embed structured data in a standardized format that search engines can parse. JSON-LD is preferred over alternatives like Microdata and RDFa because it separates the structured data from the HTML markup, making it easier to implement and maintain. Common JSON-LD types include Organization, WebSite, Article, Product, FAQ, HowTo, BreadcrumbList, and LocalBusiness. JSON-LD enables rich results in search engines, which can significantly improve click-through rates and visibility.', 'technical-seo', 'intermediate', '["structured-data", "rich-results"]'),

('Rich Results', 'rich-results', 'Enhanced search result listings that include additional visual elements like star ratings, images, prices, or FAQ dropdowns.', 'Rich results (formerly called rich snippets) are enhanced search result listings that display additional information beyond the standard title, URL, and description. They can include star ratings, product prices, recipe details, FAQ dropdowns, event dates, how-to steps, video thumbnails, and more. Rich results are generated from structured data (typically JSON-LD) added to your web pages. Pages with rich results typically see 20-30% higher click-through rates compared to standard results. Google provides a Rich Results Test tool to validate your structured data and preview how your results might appear. Not all structured data types are eligible for rich results — check Google''s documentation for supported types.', 'on-page-seo', 'intermediate', '["structured-data", "json-ld", "click-through-rate"]'),

('Competitor Analysis', 'competitor-analysis', 'The process of researching and analyzing competitor websites to identify their SEO strategies, strengths, and weaknesses.', 'Competitor analysis in SEO involves systematically researching your competitors'' websites to understand their search strategies, identify their strengths and weaknesses, and discover opportunities for your own site. Key aspects include: identifying which keywords competitors rank for, analyzing their backlink profiles, reviewing their content strategy and publishing frequency, examining their site architecture and technical SEO, and monitoring their ranking changes over time. Competitor analysis helps you benchmark your performance, discover content gaps, find link building opportunities, and understand the competitive landscape. Tools like Optic Rank automate competitor monitoring with real-time alerts for ranking changes and content updates.', 'analytics', 'intermediate', '["content-gap", "keyword-research", "backlink", "domain-authority"]'),

('Content Optimization', 'content-optimization', 'The process of improving existing content to rank better in search engines through keyword targeting, structure, and quality improvements.', 'Content optimization is the process of improving web page content to increase its relevance, quality, and search engine rankings. It involves both on-page elements (title tags, headings, meta descriptions, keyword usage) and content quality factors (depth, accuracy, freshness, readability). Key optimization techniques include: targeting specific keywords and search intent, structuring content with clear headings and logical flow, adding relevant images with alt text, including internal and external links, updating outdated information, expanding thin content, and improving readability scores. Content optimization is often more effective than creating new content because existing pages already have some authority and backlinks that can be leveraged for better rankings.', 'content-marketing', 'beginner', '["keyword-density", "on-page-seo", "eeat", "internal-linking"]'),

('International SEO', 'international-seo', 'The practice of optimizing your website for different countries and languages to rank in international search results.', 'International SEO is the practice of optimizing your website so search engines can identify which countries and languages your content targets. It involves several technical and content considerations: implementing hreflang tags to specify language and regional targeting, choosing the right URL structure (ccTLDs, subdirectories, or subdomains), creating localized content (not just translated), targeting country-specific keywords, building backlinks from local sources, and hosting on servers geographically near your target audience. Common mistakes include using automatic translation without localization, forgetting bidirectional hreflang references, and not accounting for regional search behavior differences.', 'technical-seo', 'advanced', '["hreflang", "canonical-url", "indexing"]'),

('Image SEO', 'image-seo', 'Optimizing images on your website for search engine visibility, including alt text, file names, compression, and lazy loading.', 'Image SEO is the practice of optimizing images on your website to improve their visibility in search engine image results and to enhance overall page SEO. Key image optimization techniques include: using descriptive, keyword-rich file names, writing meaningful alt text for accessibility and SEO, compressing images to reduce file size without losing quality, using modern formats (WebP, AVIF) for better compression, implementing lazy loading for below-the-fold images, specifying image dimensions to prevent layout shifts (CLS), adding images to your XML sitemap, and using responsive images with srcset for different screen sizes. Well-optimized images improve page speed, accessibility, user engagement, and can drive significant traffic from Google Images.', 'on-page-seo', 'beginner', '["alt-text", "core-web-vitals", "page-speed"]'),

('Keyword Stuffing', 'keyword-stuffing', 'The practice of overloading a page with target keywords in an unnatural way, which search engines penalize.', 'Keyword stuffing is a black-hat SEO technique that involves overloading a webpage with keywords in an unnatural way to manipulate search engine rankings. Examples include repeating the same keyword excessively, adding irrelevant keywords, using hidden text, and cramming keywords into meta tags. Search engines have sophisticated algorithms to detect keyword stuffing and will penalize pages that engage in it — either through algorithmic demotion or manual action. Instead of keyword stuffing, focus on natural keyword usage, semantic variations, and comprehensive topic coverage. A well-written page that thoroughly covers a topic will naturally include relevant keywords without manipulation.', 'on-page-seo', 'beginner', '["keyword-density", "on-page-seo", "content-optimization"]')

ON CONFLICT (slug) DO NOTHING;
